board_manager:
  additional_urls: []
build_cache:
  compilations_before_purge: 10
  ttl: 720h0m0s
daemon:
  port: '50051'
directories:
  data: /home/runner/.arduino15
  downloads: /home/runner/.arduino15/staging
  user: /home/runner/Arduino
library:
  enable_unsafe_install: true
logging:
  file: ''
  format: text
  level: info
metrics:
  addr: :9090
  enabled: true
output:
  no_color: false
sketch:
  always_export_binaries: false
updater:
  enable_notification: true
