name: build

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest

  steps:
    - name: Checkout Github Action
      uses: actions/checkout@v2

    - name: Build on Arduino CLI
      run: bash ci/build-teensy.sh
